### ISSUE TITLE
访问不了 https://ai-performance.com/embedded-ai.bench

### ISSUE THREAD

**Issue by un-knight** [AI-performance/embedded-ai.bench#26]
访问提示：
```
无法访问此网站找不到 ai-performance.com 的服务器 IP 地址。
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by ysh329** [comment]
由于各种原因，目前已经下架，如果要看过往性能，见：https://github.com/AI-performance/embedded-ai.bench/blob/master/20200809-bench:ncnn-tnn-mnn-androidv7v8-cpugpu.csv
